A .md file for Services offerings plan issue#159.
WorldEnterpriseGroup/silkcorp pull request #165
Opened 2023-04-18 17:44 UTC by Aini-Bashir

I have created a .md file based on the research I've done on this issue.

2023-04-18 17:46 UTC, Aini-Bashir commented
This PR is based on the research only I've done on this issue with the help of ChatGPT. I'll do changes as required when the PR will be approved on issue#158.

2023-04-19 18:29 UTC, Remy-Reveltek requested changes
Put the pricing model in the table, to make table use the following code:

# How to make table in markdown

## **Code:**

`| Column 1 Header | Column 2 Header | Column 3 Header |

|-----------------|-----------------|-----------------|

| Row 1, Column 1 | Row 1, Column 2 | Row 1, Column 3 |

| Row 2, Column 1 | Row 2, Column 2 | Row 2, Column 3 |

| Row 3, Column 1 | Row 3, Column 2 | Row 3, Column 3 |`

## **How it will look:**


| Column 1 Header | Column 2 Header | Column 3 Header |
|-----------------|-----------------|-----------------|
| Row 1, Column 1 | Row 1, Column 2 | Row 1, Column 3 |
| Row 2, Column 1 | Row 2, Column 2 | Row 2, Column 3 |
| Row 3, Column 1 | Row 3, Column 2 | Row 3, Column 3 |

2023-04-20 18:46 UTC, Remy-Reveltek approved these changes

2023-04-21 19:58 UTC, Remy-Reveltek approved these changes

2023-04-25 04:44 UTC, duafatimaa approved these changes

2023-04-29 19:17 UTC, merged